### ISSUE TITLE
Idea: pre-commit-hook

### ISSUE THREAD

**Issue by gkarg** [radeklat/settings-doc#14]
I think it would be a very useful feature to expose this project as a pre-commit-hook.

This way, people would be able to, say, update their README.md file automatically on each change, without running multi-step CI jobs, or doing that manually.

**Comment by radeklat** [comment]
That's a great idea! I haven't written pre-commit hooks before (only used existing ones). If anyone wants to make a PR, I'll happily review it and add it. Otherwise it will take me a while to learn how to do that and add one.
