### ISSUE TITLE
It appears sub-models are not supported

### ISSUE THREAD

**Issue by gkarg** [radeklat/settings-doc#15]
Not sure if I'm right, but it appears only the root fields of BaseSettings are exposed correctly.

From [pydantic docs](https://docs.pydantic.dev/latest/usage/settings/):

```python
class SubModel(BaseModel):
    foo = 'bar'
    apple = 1

class Settings(BaseSettings):
    more_settings: SubModel = SubModel()
    class Config:
        env_prefix = "QUX__"
        env_nested_delimiter = "__"
```

generates support for `QUX__MORE_SETTINGS__FOO` and `QUX__MORE_SETTINGS__APPLE` env vars.

I haven't yet checked if this is doable by overriding templates (it would be nice to explain that in README, if that's the case), but even if it is doable, I believe this should work by default.

**Comment by caffeinatedgaze** [comment]
I have the same issue that prefixes are ignored. This is  the only thing that stopped me from using the library. Otherwise, loving the idea

**Comment by radeklat** [comment]
Hello everyone. Both `env_prefix` and `env_nested_delimiter` should be supported since version 4.0.0. Thank you for your input and apologies for the delay. It was actually not too difficult to implement :grimacing: Please let me know if you find any use cases where it doesn't render well.
