### ISSUE TITLE
Use actual value of `Enum`

### ISSUE THREAD

**Issue by failable** [radeklat/settings-doc#39]
```python
class Env(str, Enum):
    Dev = "dev"
    Prod = "prod"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="APP__", env_nested_delimiter="__")

    env: Env = Env.Dev
```

```markdown
# `APP__ENV`

*Optional*, default value: `Env.Dev`
```

Would it better to use the "dev" value in this case?

**Comment by mssalvatore** [comment]
It works as expected for me using [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) (available in Python 3.11)

**Comment by failable** [comment]
I'm in Python 3.10.11, so it does not work for me.

**Comment by radeklat** [comment]
Thank you for your suggestion and @mssalvatore for the Python 3.11 use case. I made sure it works for both (and for `IntEnum` as well) in version 4.3.0. Additionally, I noticed example values were not rendered for enums either so I implemented that as well.

**Comment by mssalvatore** [comment]
> Additionally, I noticed example values were not rendered for enums either so I implemented that as well.

Nice! That was on my list for this week.
