### ISSUE TITLE
Usage with multiple BaseSettings classes

### ISSUE THREAD

**Issue by nesb1** [radeklat/settings-doc#4]
Hello, great project! This is exactly what people need.

In my case I need env variable docs for all new variables. And if I added a new class, then I want documentation to be generated for it and I didn't have to specify it class manualy via `-c`.

How can I use settings-doc if I have multiple settings classes? I would not like to indicate it by hand.

Have you thought about the possibility of passing only the module path or a regular expression or something like that so that the utility can independently find all the classes with settings and return results for them? 

Thx, I can help with realization:)

**Comment by radeklat** [comment]
This has been implemented in 0.6.0. There is a new option `--module`, which can be specified more than once. `--class` is now optional and also can be specified more than once.
